version: "3.9"

services:
  endee:
    image: endeeio/endee-server:latest
    ports:
      - "8080:8080"
    environment:
      NDD_NUM_THREADS: "0"
      NDD_AUTH_TOKEN: ""
    volumes:
      - endee-data:/data
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      ENDEE_HOST: http://endee:8080
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - endee

  ui:
    build: .
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      ENDEE_HOST: http://endee:8080
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - api

volumes:
  endee-data:
